# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rboreN85BlmZAthx6e1CacSI-twXNOez
"""

import random as rand
import array as arr
# By changing N we can do simulation for first N natural numbers
N=6
# number of experiments or simulations
siml_size=1000000

#declared an array of single element then appended it to have N elements initialized to 0
a=arr.array('I',[0])
i=1
while (i<N):
  a.append(0)
  i=i+1

# each element in array represents the count of no of times of occurence of (i+1) number
# simulation occurs in this loop
j=0
while (j<siml_size):
  X1=rand.randint(1,6)
  X2=rand.randint(1,6)
  if (X1>=X2):
    a[X1-1]+=1
  else:
    a[X2-1]+=1
  j+=1

# finding expextation value using the formula
i=0
Exp_val_X=0
while(i<N):
  Exp_val_X+=(a[i]*(i+1))/siml_size
  i+=1
print(f"The Expectation value obtained by simulation is : {Exp_val_X}")
# the expression used below can be obtaine from solution pdf for any general N
print(f"The value obtained by calculation is : {(4*N**2+3*N-1)/(6*N)}")